- hosts: all
  serial: 1
  gather_facts: yes
# Delegate as global?
  tasks:
  - name: Delete folder
    file:
      path: /home/ansible/ips/{{ inventory_hostname }}
      state: absent
    delegate_to: localhost
  - name: Create folder
    file:
      path: /home/ansible/ips/{{ inventory_hostname }}
      state: directory
    delegate_to: localhost
  - copy:
      content: "System {{ inventory_hostname }} has IP {{ item }}"
      dest: /home/ansible/ips/{{ inventory_hostname }}/{{ item }}
    with_items: "{{ ansible_all_ipv4_addresses }}"
    delegate_to: localhost
